version: "3"
services:
  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    command: redis-server
    volumes:
      - redis-data:/data

volumes:
  redis-data:
  mongodb_data_container:
